### ISSUE TITLE
Closed Captioning - xAPI Statements

### ISSUE THREAD

**Issue by jhaag75** [jhaag75/xapi-videojs#5]
Statements for interacting with the closed captioning button need to be added. 

Any takers?

http://docs.videojs.com/

Search videojs documentation for "caption" or "text track"

http://docs.videojs.com/tutorial-text-tracks.html

We should be able to trigger statements based on track.mode, but I couldn't find any caption events. I think we'll have to create some type of listeners based on the various functions that are triggered when you interact with the caption menu. There's a lot of options there.

**Comment by liveaspankaj** [comment]
I have found a possible solution, but there are a few issues I might need to figure out and fix first. Because it is making few extra event calls. 

One of them is probably due to this: 
```
	          // Find the English captions track and mark it as "showing".
	          if (track.kind === 'captions' || track.kind === 'subtitles' && track.language === 'en') {
	            track.mode = 'showing';
	          }
```

Is there a reason we want to enable captions and subtitles during initialization?

**Comment by liveaspankaj** [comment]
When we make any changes to track.mode like above code. it generates a track change event. 

I have commented out the above code (yet to generate pull request) so that we do not generate extra events, and I don't think we need to force subtitles or captions. 

I have been able to get the event to trigger on change of captions/subtitles. However, there is a problem. It generates multiple events. These log messages should explain:

```
change event
captions:en:disabled
subtitles:en:disabled

change event event
captions:en:disabled
subtitles:en:showing
```

These two events happen when I change from captions enabled to subtitles enabled. I believe it is happening because the background code is first disabling captions (causing first event), then enabling subtitles (causing second event). 

Let me know if you want me to commit the code for the event. 

```
var tracks 	= myPlayer.textTracks();        
tracks.addEventListener("change", function(e) {
                console.log("change");
                //console.log(e);
                for (var i = 0; i < tracks.length; i++) {
                  var track = tracks[i];
                  console.log(track.kind + ":" + track.language + ":" + track.mode);

                  // Find the English captions track and mark it as "showing".
                  //  if (track.kind === 'captions' && track.language === 'en') {
                  //  track.mode = 'showing';
                  // }
                }
        });
```

**Comment by jhaag75** [comment]
Sounds fine if you want to submit this so we can test. I think for the demo/prototype it's fine if this particular video is using captions. You can turn it off in the player by default, but for our testing purposes I would like to be able to test out all of the extensions in the video profile. 

I think it would be good if we can get this caption event to change the values of the extensions as part of the demo. We can always turn it off or create a toggle for enabling it later in case others wanted to use it.

**Comment by liveaspankaj** [comment]
I was able to figure out a way to fix multiple statements. I added a 20 millisecond delay and a flag to send statement. 

Changes commited, will do a pull request after I am made commits for other stuff. 

@jhaag75  It looks like you have reverted to force enabling closed captions and subtitles. This is now sending an extra statement on load. 
Even if we enable it, we should enable only one. i.e. closed captions or subtitle. because enabling both looks like a flawed logic, because you can enable only one manually.

**Comment by liveaspankaj** [comment]
In today's meeting it discussed and identified that forcing captions and subtitles is causing additional statements. It is also currently enabling both subtitles and captions at the same time which is not logical.
@jhaag75 decided  to look into it.

**Comment by jhaag75** [comment]
will wait until your next PR to make any changes for this
