### ISSUE TITLE
Volume Change

### ISSUE THREAD

**Issue by jhaag75** [jhaag75/xapi-videojs#9]
Take a look at xapi-videojs.js beginning around line 560. If you take a look at the number of statements being produced it seems a bit excessive. Every time the volume bar is barely moved it sends a statement for each change in the volume. We might want to look at updating this to only send the statement from the start an end point of the volume change. Could use some help looking into this.

**Comment by liveaspankaj** [comment]
committed a possible fix. 
I am tracking if slider is active or not. And sending volume change interacted statements on conditions:

Condition 1: sliderinactive event: When slider goes from active to inactive: This seems to work fine when using slider to change volume. 
Condition 2: on volume change event (but only if slider is inactive): This seems to work fine when using mute/unmute button. This should also work fine when programmatically changing the volume. 

**Edit:**
While I was writing this comment, I thought I must test it on mobile. I tried on Android, and this doesn't work. Probably because sliderinactive and slideractive events are not fired when the video is in full screen on Android. 

If anyone else knows of a way to find a better way it might be great. 

Another possible alternative is to monitor the volume changes. And, if it doesn't change during the last 1 or 2 seconds, then send the statement with timestamp and time extension value when it was last changed. 

Let me know if you would want me to try this strategy till we have a better solution?

**Comment by liveaspankaj** [comment]
Jason suggested in today's meeting that we try searching/posting the issue on VideoJS forums. 

Leaving the issue open till we find a solution.

**Comment by jhaag75** [comment]
I think we might be able to leverage this function: http://docs.videojs.com/ControlBar.html#enableTouchActivity

it listens for a "touchstart" and "touchend" event

Will post a question to the VIdeoJS community

**Comment by liveaspankaj** [comment]
Fixed volume issue, added 2 seconds of wait before sending volume change interacted statement. 
Please test.
